### ISSUE TITLE
Schema export directory is not provided to the annotation processor so we cannot export the schema.

### ISSUE THREAD

**Issue by doljko** [opengineer/memorize#28]
Schema export directory is not provided to the annotation processor so we cannot export the schema. You can either provide `room.schemaLocation` annotation processor argument OR set exportSchema to false.

**Comment by tortuvshin** [comment]
So if you don't need to check the schema and you want to get rid of the warning, just add exportSchema = false to your RoomDatabase, as follows.

```java
@Database(entities = { YourEntity.class }, version = 1, exportSchema = false)
public abstract class YourDatabase extends RoomDatabase {
   //...
}
```
